name: Build APK
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Clear GitHub Actions Cache
      run: |
        echo "Cleaning old build logs and caching..."
        rm -rf ~/.buildozer
        rm -rf .buildozer/
    - name: Install Tools
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev libbz2-dev libffi-dev
        pip install --upgrade buildozer cython kivy
    - name: Accept Android Licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo y | sdkmanager --licenses || true
    - name: Build Android APK
      run: |
        buildozer android debug
يُرج